name: Integration Tests

env:
  WORK_DIR: './src'
  APP_NAME: ${{ vars.APPROVAL_APP_NAME }}


on:
#   schedule:
#     - cron: '0 0 * * *' # 00:00 midnight UTC
# workflow_dispatch:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - master

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - run: |
      #     az webapp list --query "[?state=='Running']"
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        working-directory: ${{ env.WORK_DIR }}
        run: dotnet restore

      - name: Build        
        working-directory: ${{ env.WORK_DIR }}
        run: dotnet build --no-restore

      - name: Run Integration Tests
        working-directory: ${{ env.WORK_DIR }}
        run: dotnet test --no-restore --no-build

      - name: Print name
        run: echo "Hello $NAME. $BUILD. Using work dir $WORK_DIR. My API_KEY is ${{secrets.TEST_SECRET}}"
        env:   
            BUILD: 'We are currently running the Build job'

      - name: Test Variables and Secret
        run: |
            ls
            echo "env.AppName" ${{env.WORK_DIR}}
            echo "env.AppName - ${{env.APP_NAME}}"
            echo "vars.AppName - ${{vars.APPROVAL_APP_NAME}}"
            echo "secret - ${{secrets.TEST_SECRET}}"

          
